jdbc.driverClassName=${DB_DRIVER:com.mysql.cj.jdbc.Driver}
jdbc.url=${DB_URL:jdbc:mysql://localhost:3306/accounts?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=CONVERT_TO_NULL&serverTimezone=UTC}
jdbc.username=${DB_USERNAME}
jdbc.password=${DB_PASSWORD}
