# SonarQube project configuration for SonarScanner for Maven
sonar.projectKey=vprofile
sonar.projectName=VProfile
sonar.sourceEncoding=UTF-8
sonar.java.source=8
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
